[package]
name = "weft-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "weft-pack"
path = "src/main.rs"

[dependencies]
weft-ipc-types = { path = "../weft-ipc-types" }
anyhow = "1.0"
ed25519-dalek = { version = "2", features = ["rand_core"] }
sha2 = "0.10"
rand = "0.8"
hex = "0.4"
tar = "0.4"
zstd = "0.13"

[target.'cfg(unix)'.dependencies]
rustix = { version = "1", features = ["fs"] }
